[package]
name = "encryption"
version = "0.1.0"
edition = '2021'

[lib]
crate-type = ["cdylib"]

[dependencies]
mariadb-server = { path = "../../mariadb" }
aes-gcm = "0.10"
sha2 = "0.10"
rand = "0.8"
