[package]
name = "mariadb-macros"
version = "0.1.0"
edition = "2021"


[lib]
proc-macro = true

[dependencies]
# heck = "0.4.0"
# lazy_static = "1.4.0"
proc-macro2 = "1.0.49"
quote = "1.0.23"
syn = { version = "1.0.107", features = [], default-features = false }
# syn = { version = "1.0.107", features = ["full", "extra-traits", "parsing"] }

[dev-dependencies]
# trybuild = { version = "1.0.65", features = ["diff"] }
mariadb = { path = "../mariadb" }
